### ISSUE TITLE
Please support typeguard version 3

### ISSUE THREAD

**Issue by musicinmybrain** [kalekundert/signature_dispatch#3]
Version 3.0.0 of `typeguard` [has been released](https://github.com/agronholm/typeguard/releases/tag/3.0.0) with [breaking changes](https://github.com/agronholm/typeguard/blob/3.0.0/docs/versionhistory.rst).

The change that most immediately impacts this package is that the initial `argname` parameter is removed from `typeguard.check_type`. This causes quite a few tests to fail ([log attached](https://github.com/kalekundert/signature_dispatch/files/10980777/typeguard-3-test.txt)).

If I work around that change (for which I am happy to offer a PR, if you let me know whether you want to maintain backward compatibility with typeguard 2.x or not), I find that there are still quite a few failures ([log attached](https://github.com/kalekundert/signature_dispatch/files/10980778/typeguard-3-test-check_type-fixed.txt)).

**Comment by kalekundert** [comment]
Thanks for the heads up.  This should be fixed now.  I'm actually glad they made that change to `typeguard.check_type()`; the old API was quite awkward.

**Comment by musicinmybrain** [comment]
Thanks; that was fast! Version 1.0.1 is working for me.
